import fs from 'node:fs/promises';
import path from 'node:path';
import {
  ASSISTANTS,
  CONFIG_NAME,
  CONFIG_RELATIVE_PATH,
  CONFIG_VERSION,
  DEFAULT_OUTPUTS,
  LEGACY_CONFIG_NAME,
  LEGACY_PROJECT_CONFIG_NAME,
  MID_DIR_NAME
} from './constants.js';
import { unique } from './utils.js';

function normalizeModuleId(value) {
  if (value.startsWith('core.optional.')) {
    return `core.${value.slice('core.optional.'.length)}`;
  }
  return value;
}

export function createDefaultConfig() {
  return {
    version: CONFIG_VERSION,
    standardsRevision: 'unknown',
    assistants: [],
    general: [],
    languages: [],
    frameworks: [],
    outputs: { ...DEFAULT_OUTPUTS }
  };
}

export function getMidDirPath(projectRoot) {
  return path.join(projectRoot, MID_DIR_NAME);
}

export function getConfigPath(projectRoot) {
  return path.join(projectRoot, CONFIG_RELATIVE_PATH);
}

function parseConfig(raw, config, warning = null) {
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex === -1) {
      continue;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    const value = trimmed.slice(separatorIndex + 1).trim();

    switch (key) {
      case 'version':
        if (value !== CONFIG_VERSION) {
          throw new Error(`Unsupported ${CONFIG_NAME} version: ${value}`);
        }
        config.version = value;
        break;
      case 'standards_revision':
        config.standardsRevision = value || 'unknown';
        break;
      case 'assistant':
        config.assistants.push(value);
        break;
      case 'general':
        config.general.push(normalizeModuleId(value));
        break;
      case 'language':
        config.languages.push(value);
        break;
      case 'framework':
        config.frameworks.push(value);
        break;
      case 'output.codex':
        config.outputs.codex = value;
        break;
      case 'output.claude':
        config.outputs.claude = value;
        break;
      case 'output.cursor':
        config.outputs.cursor = value;
        break;
      case 'output.general':
        config.outputs.general = value;
        break;
      default:
        break;
    }
  }

  config.assistants = unique(config.assistants);
  config.general = unique(config.general);
  config.languages = unique(config.languages);
  config.frameworks = unique(config.frameworks);

  return { config, warning };
}

export async function loadConfig(projectRoot) {
  const configPath = getConfigPath(projectRoot);
  const config = createDefaultConfig();
  let raw;

  try {
    raw = await fs.readFile(configPath, 'utf8');
  } catch (error) {
    if (error && error.code === 'ENOENT') {
      try {
        raw = await fs.readFile(path.join(projectRoot, LEGACY_PROJECT_CONFIG_NAME), 'utf8');
        return parseConfig(raw, config, `${LEGACY_PROJECT_CONFIG_NAME} is deprecated. Re-run mid to migrate it to ${CONFIG_RELATIVE_PATH}.`);
      } catch (legacyError) {
        if (!legacyError || legacyError.code !== 'ENOENT') {
          throw legacyError;
        }
      }

      try {
        await fs.access(path.join(projectRoot, LEGACY_CONFIG_NAME));
        return { config: null, warning: `${LEGACY_CONFIG_NAME} is no longer used. Re-run mid to create ${CONFIG_RELATIVE_PATH}.` };
      } catch {
        return { config: null, warning: null };
      }
    }
    throw error;
  }

  return parseConfig(raw, config, null);
}

export async function saveConfig(projectRoot, config) {
  const lines = [
    '# Generated by mid. Edit with care.',
    `version=${CONFIG_VERSION}`,
    `standards_revision=${config.standardsRevision}`
  ];

  for (const assistant of config.assistants) {
    lines.push(`assistant=${assistant}`);
  }
  for (const value of config.general) {
    lines.push(`general=${value}`);
  }
  for (const value of config.languages) {
    lines.push(`language=${value}`);
  }
  for (const value of config.frameworks) {
    lines.push(`framework=${value}`);
  }

  lines.push(`output.codex=${config.outputs.codex}`);
  lines.push(`output.claude=${config.outputs.claude}`);
  lines.push(`output.cursor=${config.outputs.cursor}`);
  lines.push(`output.general=${config.outputs.general}`);

  await fs.mkdir(getMidDirPath(projectRoot), { recursive: true });
  const configPath = getConfigPath(projectRoot);
  await fs.writeFile(configPath, `${lines.join('\n')}\n`, 'utf8');
  await fs.rm(path.join(projectRoot, LEGACY_PROJECT_CONFIG_NAME), { force: true }).catch(() => {});
  return configPath;
}

export function validateConfigSelection(config, modules, strict = true) {
  const validAssistants = new Set(ASSISTANTS.map((assistant) => assistant.id));
  const moduleById = new Map(modules.map((module) => [module.id, module]));
  const issues = [];

  const assistants = config.assistants.filter((assistant) => validAssistants.has(assistant));
  if (assistants.length !== config.assistants.length) {
    issues.push('config contains unknown assistants');
    config.assistants = assistants;
  }

  if (strict && config.assistants.length === 0) {
    throw new Error(`${CONFIG_NAME} must select at least one assistant.`);
  }

  for (const [key, expectedGroup] of [
    ['general', 'general'],
    ['languages', 'language'],
    ['frameworks', 'framework']
  ]) {
    config[key] = config[key].map((id) => (key === 'general' ? normalizeModuleId(id) : id));
    const filtered = config[key].filter((id) => moduleById.get(id)?.group === expectedGroup);
    if (filtered.length !== config[key].length) {
      issues.push(`config contains invalid ${key}`);
      config[key] = filtered;
    }
  }

  if (strict && issues.length > 0) {
    throw new Error(`Invalid entries in ${CONFIG_NAME}. Re-run mid to refresh the selections.`);
  }

  return issues;
}
